### ISSUE TITLE
Error when compling libcore: double free or corruption (!prev): 0x0000000812b24420 ***

### ISSUE THREAD

**Issue by thesam** [thesam/rust-cross-kfreebsd#2]
```
Starting program: /home/samme/rustcnopie /home/samme/git/rust/src/libcore/lib.rs
*** Error in `/home/samme/rustcnopie': double free or corruption (!prev): 0x0000000812b24420 ***

Program received signal SIGABRT, Aborted.
__syscall_thr_kill () at ../sysdeps/unix/syscall-template.S:73
73  ../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  __syscall_thr_kill () at ../sysdeps/unix/syscall-template.S:73
#1  0x00000008014a36c9 in __GI_raise (sig=sig@entry=6) at ../ports/sysdeps/unix/bsd/bsd4.4/kfreebsd/fbtl/raise.c:43
#2  0x00000008014a4529 in __GI_abort () at abort.c:89
#3  0x00000008014dfe1d in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x801599a60 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#4  0x00000008014e51de in malloc_printerr (action=1, str=0x801599b68 "double free or corruption (!prev)", ptr=<optimized out>) at malloc.c:4996
#5  0x00000008077ea9a0 in llvm::PassManagerBuilder::~PassManagerBuilder() () from /home/samme/rs/deps/librustc_llvm-3788005abce0b336.so
#6  0x00000008077ec28e in LLVMPassManagerBuilderDispose () from /home/samme/rs/deps/librustc_llvm-3788005abce0b336.so
#7  0x00000008025a5130 in rustc_trans::back::write::with_llvm_pmb::hd9dac866d5574e81 () from /home/samme/rs/deps/librustc_trans-310fe5271ab2bc5f.so
#8  0x000000080259f8fe in rustc_trans::back::write::optimize_and_codegen::h117ed7759fcfdfae () from /home/samme/rs/deps/librustc_trans-310fe5271ab2bc5f.so
#9  0x00000008025a2d90 in rustc_trans::back::write::execute_work_item::h1eb4487856729a4a () from /home/samme/rs/deps/librustc_trans-310fe5271ab2bc5f.so
#10 0x00000008025a3041 in rustc_trans::back::write::run_work_singlethreaded::h7d10dba75796a50e () from /home/samme/rs/deps/librustc_trans-310fe5271ab2bc5f.so
#11 0x00000008025a2154 in rustc_trans::back::write::run_passes::h9b10a6b5e0a8c8bb () from /home/samme/rs/deps/librustc_trans-310fe5271ab2bc5f.so
#12 0x0000000800bb5c6d in rustc_driver::driver::phase_5_run_llvm_passes::_$u7b$$u7b$closure$u7d$$u7d$::hcdb2ab90f48a562d () from /home/samme/rs/deps/librustc_driver-f018673d9722bf61.so
#13 0x00000008009552da in rustc::util::common::time::he38225008ae05cd1 () from /home/samme/rs/deps/librustc_driver-f018673d9722bf61.so
#14 0x0000000800b86dd8 in rustc_driver::driver::phase_5_run_llvm_passes::h44b5c966bc1af2d2 () from /home/samme/rs/deps/librustc_driver-f018673d9722bf61.so
#15 0x0000000800b7e8b4 in rustc_driver::driver::compile_input::h3737ef608cda9baf () from /home/samme/rs/deps/librustc_driver-f018673d9722bf61.so
#16 0x0000000800b94663 in rustc_driver::run_compiler_with_file_loader::h2669f00f659269d8 () from /home/samme/rs/deps/librustc_driver-f018673d9722bf61.so
#17 0x0000000800b933d0 in rustc_driver::run_compiler::h3cb64d086372bf6b () from /home/samme/rs/deps/librustc_driver-f018673d9722bf61.so
#18 0x0000000800bebab1 in rustc_driver::run::_$u7b$$u7b$closure$u7d$$u7d$::hc2431f722285a302 () from /home/samme/rs/deps/librustc_driver-f018673d9722bf61.so
#19 0x0000000800be6efe in rustc_driver::monitor::_$u7b$$u7b$closure$u7d$$u7d$::h8590acbced381ba5 () from /home/samme/rs/deps/librustc_driver-f018673d9722bf61.so
#20 0x0000000800b56840 in _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::ha7b525ab6c587307 ()
   from /home/samme/rs/deps/librustc_driver-f018673d9722bf61.so
#21 0x0000000800ba7ac3 in std::panicking::try::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2760fc9fa9ce62ec () from /home/samme/rs/deps/librustc_driver-f018673d9722bf61.so
#22 0x000000080089cb3e in std::panicking::try::call::h3b74a88eda0dfbdb () from /home/samme/rs/deps/librustc_driver-f018673d9722bf61.so
#23 0x000000080100c877 in __rust_maybe_catch_panic () from /home/samme/rs/lib/rustlib/x86_64-unknown-kfreebsd-gnu/lib/libstd-f53fb285.so
#24 0x0000000800ba7a1b in std::panicking::try::_$u7b$$u7b$closure$u7d$$u7d$::hde065a78bd01a354 () from /home/samme/rs/deps/librustc_driver-f018673d9722bf61.so
#25 0x00000008008bf2dd in _$LT$std..thread..local..LocalKey$LT$T$GT$$GT$::with::hd8f3e021a024d780 () from /home/samme/rs/deps/librustc_driver-f018673d9722bf61.so
#26 0x000000080089ca69 in std::panicking::try::hb476caed6f0e3af2 () from /home/samme/rs/deps/librustc_driver-f018673d9722bf61.so
#27 0x000000080089c058 in std::panic::catch_unwind::h3a72fa92b978bf23 () from /home/samme/rs/deps/librustc_driver-f018673d9722bf61.so
#28 0x0000000800ba781c in std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::h74b963dccc20d1f7 () from /home/samme/rs/deps/librustc_driver-f018673d9722bf61.so
#29 0x00000008008ffafe in _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::hbaaea021a3b9f108 () from /home/samme/rs/deps/librustc_driver-f018673d9722bf61.so
#30 0x0000000800ffb9e9 in std::sys::thread::Thread::new::thread_start::h2e98425c7fffa990 () from /home/samme/rs/lib/rustlib/x86_64-unknown-kfreebsd-gnu/lib/libstd-f53fb285.so
#31 0x000000080b9f4ae7 in start_thread (arg=0x80d92e6c0) at pthread_create.c:311
#32 0x0000000000000000 in ?? ()
```

**Comment by thesam** [comment]
This problem disappeared when I started using the correct LLVM_CONFIG (llvm-config-host from the cross-compiled LLVM).
